#!/usr/bin/env node
/**
 * tools/report.js: publish a snapshot of the order book into the repository, so AI tools
 * that can read the repo (e.g. DevRev Computer via its GitHub connector) can answer
 * questions about orders and sales performance.
 *
 *   npm run report           write reports/sales-snapshot.md and data/orders.csv
 *   npm run report:publish   the same, then git add + commit + push
 *
 * The snapshot is a point-in-time copy: re-run it whenever the data should be current.
 */
const { execFileSync } = require('child_process');
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
try { process.loadEnvFile(path.join(ROOT, '.env')); } catch { /* no .env file */ }

const store = require('../store');
const { leadershipDashboard, repDashboard, staleOrders, formatMoney, formatPct, STALE_HOURS } = require('../metrics');
const { buildInsights } = require('../insights');

const WINDOW_DAYS = 28;
const RECENT_LIMIT = 25;

const publish = process.argv.includes('--publish');
const generatedAt = new Date();

/* ------------------------------------------------------------------ */
/* Helpers                                                             */
/* ------------------------------------------------------------------ */

const day = (iso) => String(iso).slice(0, 10);
const signed = (value, unit = '%') => (value === null || value === undefined ? 'n/a' : `${value >= 0 ? '+' : ''}${value}${unit}`);

/** Markdown table from a header row and value rows. */
function table(headers, rows) {
  const lines = [`| ${headers.join(' | ')} |`, `|${headers.map(() => '---').join('|')}|`];
  for (const row of rows) lines.push(`| ${row.join(' | ')} |`);
  return lines.join('\n');
}

const csvCell = (value) => {
  const text = value === null || value === undefined ? '' : String(value);
  return /[",\n]/.test(text) ? `"${text.replace(/"/g, '""')}"` : text;
};
const csv = (headers, rows) => [headers, ...rows].map((row) => row.map(csvCell).join(',')).join('\n');

/* ------------------------------------------------------------------ */
/* Snapshot                                                            */
/* ------------------------------------------------------------------ */

function buildMarkdown(orders, reps) {
  const dash = leadershipDashboard(orders, reps, { days: WINDOW_DAYS });
  const k = dash.kpis;
  const insights = buildInsights(orders);
  const stale = staleOrders(orders);
  const recent = orders.slice(0, RECENT_LIMIT);

  const repRows = dash.reps.map((r) => [
    r.name, r.region, r.orders, formatMoney(r.revenue), formatMoney(r.quota), formatPct(r.attainment),
    formatMoney(r.avg_order_value), r.open_orders, r.stale_orders,
  ]);
  const monthRows = reps.map((rep) => {
    const view = repDashboard(orders, reps, rep.id).month;
    return [rep.name, formatMoney(view.revenue), formatMoney(view.quota), formatPct(view.attainment),
      { on_track: 'On track', at_risk: 'At risk', behind: 'Behind pace' }[view.pace] || 'n/a', `#${view.team_rank} of ${view.team_size}`];
  });

  return `# OrderDesk sales snapshot

**Generated:** ${generatedAt.toISOString()} · **Window:** last ${WINDOW_DAYS} days (${day(dash.range.start)} to ${day(dash.range.end)})

This file is a point-in-time export from OrderDesk, a field sales order management system.
It is generated by \`npm run report\`; do not edit it by hand. The full order list is in
[\`../data/orders.csv\`](../data/orders.csv).

## How to read this data

- **Order:** one purchase placed by a field sales rep for a customer. Value = quantity × unit price.
- **Status:** New → Processing → Shipped → Delivered, or Cancelled. "Open" means New or Processing.
- **Booked revenue:** total value of orders that are not Cancelled.
- **Quota attainment:** booked revenue ÷ quota. For a ${WINDOW_DAYS}-day window the monthly quota is prorated (× ${WINDOW_DAYS}/30).
- **Needs attention / stale:** an open order with no update for ${STALE_HOURS} hours or more.
- **Captured offline:** the order was taken without connectivity on a mobile device and synced later.

## Headline numbers (last ${WINDOW_DAYS} days)

${table(['Metric', 'Value', 'Change vs previous ' + WINDOW_DAYS + ' days'], [
  ['Booked revenue', formatMoney(k.revenue), signed(k.revenue_change_pct)],
  ['Orders', k.orders, signed(k.orders_change_pct)],
  ['Average order value', formatMoney(k.avg_order_value), signed(k.avg_order_value_change_pct)],
  ['Quota attainment', formatPct(k.attainment), `${formatMoney(k.revenue)} of ${formatMoney(k.quota)} prorated quota`],
  ['Open pipeline', formatMoney(k.open_pipeline_value), `${k.open_orders} open orders`],
  ['Captured offline', formatPct(k.offline_share), signed(k.offline_share_change_pts, ' pts')],
])}

## Reps (last ${WINDOW_DAYS} days)

${table(['Rep', 'Region', 'Orders', 'Booked revenue', 'Quota', 'Attainment', 'Avg order', 'Open', 'Stale'], repRows)}

## Reps, month to date

${table(['Rep', 'Revenue', 'Monthly quota', 'Attainment', 'Pace', 'Team rank'], monthRows)}

## Regions (last ${WINDOW_DAYS} days)

${table(['Region', 'Reps', 'Orders', 'Booked revenue', 'Attainment'], dash.regions.map((r) => [r.region, r.reps, r.orders, formatMoney(r.revenue), formatPct(r.attainment)]))}

## Pipeline by stage (orders created in the window)

${table(['Stage', 'Orders', 'Value'], dash.pipeline.map((s) => [s.status, s.orders, formatMoney(s.value)]))}

## Needs attention: open orders with no update for ${STALE_HOURS}h or more

${stale.length === 0 ? '_None: every open order was updated recently._' : table(
  ['Order', 'Customer', 'Product', 'Value', 'Status', 'Rep', 'Region', 'No update for'],
  stale.slice(0, 20).map((o) => [`#${o.id}`, o.customer_name, o.product, formatMoney(o.total), o.status, o.rep_name, o.rep_region,
    o.hours_since_update >= 48 ? `${Math.floor(o.hours_since_update / 24)} days` : `${o.hours_since_update} hours`]),
)}

## Most recent orders

${table(['Order', 'Created', 'Customer', 'Product', 'Qty', 'Value', 'Status', 'Rep', 'Captured'],
  recent.map((o) => [`#${o.id}`, day(o.created_at), o.customer_name, o.product, o.quantity, formatMoney(o.total), o.status, o.rep_name, o.placed_offline ? 'Offline' : 'Online']))}

## All orders, all time

${insights.summary}

${table(['Metric', 'Value'], [
  ['Orders', insights.total],
  ['Units', insights.units],
  ['Booked value', formatMoney(insights.booked_value)],
  ['Open orders', insights.open],
  ['Sales reps', reps.length],
  ['Orders needing attention', stale.length],
])}
`;
}

function buildCsv(orders) {
  return csv(
    ['id', 'created_at', 'updated_at', 'customer_name', 'product', 'quantity', 'unit_price', 'total', 'status', 'rep_name', 'rep_region', 'placed_offline'],
    orders.map((o) => [o.id, o.created_at, o.updated_at, o.customer_name, o.product, o.quantity, o.unit_price, o.total, o.status, o.rep_name, o.rep_region, o.placed_offline]),
  );
}

/* ------------------------------------------------------------------ */
/* Run                                                                 */
/* ------------------------------------------------------------------ */

store.init();
const orders = store.listOrders();
const reps = store.listReps();

const markdownPath = path.join(ROOT, 'reports', 'sales-snapshot.md');
const csvPath = path.join(ROOT, 'data', 'orders.csv');
fs.mkdirSync(path.dirname(markdownPath), { recursive: true });
fs.mkdirSync(path.dirname(csvPath), { recursive: true });
fs.writeFileSync(markdownPath, buildMarkdown(orders, reps));
fs.writeFileSync(csvPath, `${buildCsv(orders)}\n`);

console.log(`Wrote reports/sales-snapshot.md and data/orders.csv (${orders.length} orders, ${reps.length} reps).`);

if (!publish) {
  console.log('Run "npm run report:publish" to commit and push the snapshot to GitHub.');
  process.exit(0);
}

const git = (...args) => execFileSync('git', args, { cwd: ROOT, encoding: 'utf8' });
git('add', 'reports/sales-snapshot.md', 'data/orders.csv');
if (git('diff', '--cached', '--name-only').trim() === '') {
  console.log('Snapshot unchanged: nothing to commit.');
  process.exit(0);
}
git('commit', '-m', `Update sales snapshot (${generatedAt.toISOString().slice(0, 16).replace('T', ' ')} UTC)`);
console.log(git('push').trim() || 'Pushed.');
console.log('Pushed. AI tools reading the repository will pick it up on their next index.');
